<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX716ubn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX716ubn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX716ubn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX716ubn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX716ubn\appProdProjectContainer([
    'container.build_hash' => 'X716ubn',
    'container.build_id' => '1abae0e1',
    'container.build_time' => 1692299752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX716ubn');
